runtime: nodejs20
service: frontend

handlers:
- url: /
  static_files: dist/frontend/browser/index.html
  upload: dist/frontend/browser/index.html

- url: /(.*\.(js|css|ico|png|jpg|jpeg|svg|woff|woff2|ttf|eot|json))
  static_files: dist/frontend/browser/\1
  upload: dist/frontend/browser/(.*\.(js|css|ico|png|jpg|jpeg|svg|woff|woff2|ttf|eot|json))

- url: /(.*)
  static_files: dist/frontend/browser/index.html
  upload: dist/frontend/browser/index.html

env_variables:
  NODE_ENV: "production"

instance_class: F1
