runtime: python39
service: default
instance_class: F4
entrypoint: bash -c "mkdir -p /tmp/processing /tmp/uploads && python diagnose.py && gunicorn -t 300 -b 0.0.0.0:8080 -w 2 -k uvicorn.workers.UvicornWorker main:app"

# Add routing handlers for App Engine to properly direct requests
handlers:
  # Route all traffic to the application
  - url: /.*
    script: auto
    secure: optional

# Health check configuration
health_check:
  enable_health_check: true
  check_interval_sec: 30
  timeout_sec: 10
  unhealthy_threshold: 3
  healthy_threshold: 2

# Environment variables
env_variables:
  # Basic settings
  SESSION_SECRET_KEY: "dev-secret-replace-in-production"
  GOOGLE_CLOUD_PROJECT: "conference-cms-project"

  # Auth settings - App Engine will use the default service account
  GOOGLE_APPLICATION_CREDENTIALS: ""  # Keep empty to use default credentials
  USE_APP_ENGINE_CREDENTIALS: "true"
  
  # OAuth configuration - Set to true when OAuth is needed
  GOOGLE_CLIENT_ID: ""
  GOOGLE_CLIENT_SECRET: ""
  GOOGLE_AUTH_DISABLED: "true"  # Change to "false" when enabling OAuth

  # Frontend URL for redirects
  FRONTEND_URL: "https://conference-cms-project.uw.r.appspot.com"

  # Debug flag - Set to true to see more detailed errors
  DEBUG: "true"

  # Feature flags - Enable cloud storage
  USE_GCS: "true"
  USE_CLOUD_TASKS: "false"  # Enable when needed

  # AI/ML Settings
  VERTEX_RAG_MODEL: "text-bison"

  # Storage settings - Google Cloud Storage configuration
  GCS_BUCKET_NAME: "conference-cms-project-content"
  GCS_FOLDER_PREFIX: "uploads"
  GCS_MAKE_PUBLIC: "false"
  GCS_URL_EXPIRATION: "86400"  # 24 hours in seconds
  
  # Temporary processing directories
  TEMP_PROCESSING_DIR: "/tmp/processing"
  TEMP_UPLOAD_DIR: "/tmp/uploads"
  UPLOAD_DIR: "/tmp/uploads"
  
  # Cloud Tasks settings
  GCP_LOCATION: "us-central1"
  VECTOR_PROCESSING_QUEUE: "vector-processing"

  # Firestore settings
  FIRESTORE_PROJECT_ID: "conference-cms-project"
  
  # OpenAPI Schema Generation
  OPENAPI_SIMPLE_MODE: "true"
  DISABLE_OPENAPI_VALIDATION: "true"
