version: '3'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - FIRESTORE_EMULATOR_HOST=firestore:8080
      - FIRESTORE_PROJECT_ID=conference-cms
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json
      - SESSION_SECRET_KEY=devkeyforsessions
    depends_on:
      - firestore
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  firestore:
    image: mtlynch/firestore-emulator:latest
    ports:
      - "8080:8080"
    environment:
      - FIRESTORE_PROJECT_ID=conference-cms 